#!/bin/bash


./comp.sh &> comp.log

compOK=`grep -c 'EVR OK' comp.log `
echo compOK $compOK
if [ $compOK = '0' ]
then
 echo " ElVibRot compilation: ERROR"
 exit
fi

test_size=$1

if [ -z $test_size ]
then
  test_size=small
fi


if [ $test_size = 'big' ]
then
 echo " Big tests"
fi

if [ $test_size = 'small' ]
then
 echo " Small tests"

 echo " dat_publi_HADA" >> err.log
 ./DAT_files/dat_publi_HADA >> err.log 2>&1
 ./CompareLevel res_HADA_HarD lev_res_HADA_HarD Table2_JCP2001-1+2D.txt 2

 echo " dat_publi_cHAC 3" >> err.log
 ./DAT_files/dat_publi_cHAC 3 >> err.log 2>&1
 ./CompareLevel res_cHAC_HarD lev_res_cHAC_HarD Table2_JCP2001-1+2D.txt 4

 echo " dat_publi-Murrell f 5" >> err.log
 ./DAT_files/dat_publi-Murrell f 5 >> err.log 2>&1
 ./CompareLevel res_cHAC_Exact lev_res_cHAC_Exact Table2_JCP2001-1+2D.txt 6 1.

 echo " dat_publi-Murrell t 11" >> err.log
 ./DAT_files/dat_publi-Murrell t 11 >> err.log 2>&1
 ./CompareLevel res_cHAC_Exact lev20_res_cHAC_Exact Table_CV-1+2D.txt 5 0.1
fi

if [ $test_size = 'medium' ]
then
 echo " Medium tests"

 echo " dat_publi_HADA" >> err.log
 ./DAT_files/dat_publi_HADA >> err.log 2>&1
 ./CompareLevel res_HADA_HarD lev_res_HADA_HarD Table2_JCP2001-1+2D.txt 2

 echo " dat_publi_cHAC 11" >> err.log
 ./DAT_files/dat_publi_cHAC 11 >> err.log 2>&1
 ./CompareLevel res_cHAC_HarD lev_res_cHAC_HarD Table2_JCP2001-1+2D.txt 4

 echo " dat_publi-Murrell f 11" >> err.log
 ./DAT_files/dat_publi-Murrell f 11 >> err.log 2>&1
 ./CompareLevel res_cHAC_Exact lev_res_cHAC_Exact Table2_JCP2001-1+2D.txt 6 1.
 ./CompareLevel res_cHAC_Exact lev20_res_cHAC_Exact Table_CV-1+2D.txt 5 0.1

 echo " dat_publi-Murrell t 16" >> err.log
 ./DAT_files/dat_publi-Murrell t 16 >> err.log 2>&1
 ./CompareLevel res_cHAC_Exact lev20_res_cHAC_Exact Table_CV-1+2D.txt 5 0.1
fi
