#!/bin/bash

test_size=$1

./clean

if [ -z $test_size ]
then
  test_size=small
fi
if [ $test_size = 'small' ]
then
 echo " Small tests"
 echo " Small tests" > run_tests.log
fi

 ./calc_5D   $test_size >> run_tests.log



nb_err=`grep -c "ERROR" run_tests.log`
if [ $nb_err -eq 0 ]
then
  echo "NO ERROR in CLATHRATE_SPCE UT"
else
  grep "ERROR" run_tests.log
  echo $nb_err " ERROR(S) in CLATHRATE_SPCE UT"
  echo  " check the output files and run_tests.log in UnitTests/CLATHRATE_SPCE."
fi
