#!/bin/bash

#remove the links
rm -fr QDUtilLib AD_dnSVM ConstPhys QuantumModelLib nDindex EVRT_dnSVM FOR_EVRT Tnum-Tana

for dirlib in *_loc
do
  echo $dirlib
  test -d $dirlib || continue
  cd $dirlib
  make --silent cleanall &> /dev/null
  cd ..
done

#special procedure for ARPACK
dirlib=ARPACK_EVR
echo $dirlib
test -d $dirlib || continue
  cd $dirlib
  make --silent cleanlib &> /dev/null
  cd ..

